In [1]:
import numpy as np

a = [5,4,7]
b = [3,4,2]

c = list(map(lambda a,b: a*b,a,b))
print(c)

[15, 16, 14]


In [3]:
# We cant do like this
a = [5,4,7]
b = [3,4,2]

c = a*b
print(c)

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
a = [5,4,7]
b = [3,4,2]
c = []

for i in range(len(a)):
    c.append(a[i]*b[i])
    
print(c)

[15, 16, 14]


In [3]:
a = np.array(a)
print(a)

[5 4 7]


In [4]:
b = np.array(b)
print(b)

[3 4 2]


In [5]:
c = a*b
print(c)

[15 16 14]


In [ ]:
# METHOD 1: First make a list and then pass it in numpy

In [1]:
# Importing the module

import numpy as np

# Creating the list

list = [100,200,300]

# Creating 1-d array

n = np.array(list)
print(n)

print()

print(type(n))

[100 200 300]

<class 'numpy.ndarray'>


In [ ]:
# METHOD 2: arange() returns evenly spaced values within a given interval

In [4]:
# Creating a numpy array using arange() - array range

# Values from 2 to 10 are arranged in numpy array with interval of 2

x = np.arange(2,12,2)
y = np.arange(10,5,-2)

print(x)
print(y)

print()

print(type(x))

[ 2  4  6  8 10]
[10  8  6]

<class 'numpy.ndarray'>


In [3]:
# from 2 to 11, 3 values are fetched dividing the interval into equal parts and initialized as numpy array

x = np.linspace(2,11,4)
print(x)
print(type(x))

[ 2.  5.  8. 11.]
<class 'numpy.ndarray'>


In [15]:
x = np.linspace(2,15,4)  # linspace - linear space 4-it split equal parts
print(x)
print(type(x))

[ 2.          6.33333333 10.66666667 15.        ]
<class 'numpy.ndarray'>


## Shape of numpy array

In [17]:
y = np.array([1,2,3,4,5,6,7,8,9])
print(y.shape)
print()
z = np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(z)
print()
print(z.shape)

(9,)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]

(2, 9)


In [20]:
print(y.ndim)
print(z.ndim)

1
2


In [ ]:
#Use documentation for packages.. numpy.org search and find in chrome for documentation purpose
# list - heterogeneous
# numpy - homogeneous

In [6]:
# initialized in the form of nested python lists 

np_arr = np.array([[1,2,3],[4,5,6]])

print(np_arr)

[[1 2 3]
 [4 5 6]]


In [7]:
np_arr.shape

(2, 3)

In [8]:
np_arr.size

6

In [9]:
np_arr.ndim

2

In [23]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
y.shape

(3, 3)

In [25]:
y.size

9

In [26]:
y.ndim

2

In [27]:
print(type(y))   # ndarray - n-dimensional array

<class 'numpy.ndarray'>


## Zeros() and Ones() function

#### Zeros()

In [32]:
# Create a 3*3 array initialized with 0s.

np_arr = np.zeros((3,3))
print(np_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
np_arr = np.zeros((3,3),dtype = np.int64)
print(np_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
np_arr.shape

(3, 3)

#### Ones()

In [ ]:
# ones() fn works like the zeros() fn, but all array elements aray initialized to 1.

In [37]:
# Creating a 3*3 array initialized with 1s

a = np.ones((3,2,4),dtype = np.int32)   # (3,2,4)- 3 D 2 Row 4 Column
print(a)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [16]:
a = np.ones((3,3,2,4),dtype = np.int32)   # (3,3,2,4)- 4-Dimensinlaity 3-3D 3-2D 2 Row 4 Column
print(a)

[[[[1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]]]]


In [ ]:
# Calculations

In [18]:
# initialize the value
import numpy as np

a = [[1,5,8],[8,5,4],[6,3,2],[5,4,2]]

# converting list to array
x = np.array(a)

# displaying list
print(a)

# displaying array
print(x)
print(np.mean(a,axis=1))  # axis=1 means it takes rows axis=0 means it takes column vise...
print(np.std(a,axis=0))
print(np.median(a,axis=0))
print(np.var(a,axis=0))

[[1, 5, 8], [8, 5, 4], [6, 3, 2], [5, 4, 2]]
[[1 5 8]
 [8 5 4]
 [6 3 2]
 [5 4 2]]
[4.66666667 5.66666667 3.66666667 3.66666667]
[2.54950976 0.8291562  2.44948974]
[5.5 4.5 3. ]
[6.5    0.6875 6.    ]


In [19]:
print(np.mean(a,axis=0))

[5.   4.25 4.  ]


## Indexing and Slicing

#### Indexing can be done is numpy by using an array as an index
#### In case of slicing a view or shallow copy of the array is returned but in index array a copy of the original array is returned

In [22]:
a = np.arange(50,80)

print(a)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79]


In [23]:
# Indexing

print(a[5])

55


In [24]:
# Slicing

print(a[5:25:8])  # [start:stop:skip]

[55 63 71]


In [25]:
# Fetching elements from a specific element to the end

print(a[20:])

[70 71 72 73 74 75 76 77 78 79]


In [26]:
# Fetching elements from index 0 to specific element

print(a[:5])

[50 51 52 53 54]


In [27]:
# Create a sequence of integers from 10 to 1 with a step of -2

a = np.arange(10,1,-2)
print("\n A sequential array with a negative step: \n",a)

print()
new = a[1:4]
print(new)


 A sequential array with a negative step: 
 [10  8  6  4  2]

[8 6 4]


## VECTORS & MATRICES

#### vectors and matrices are both fundamental mathematical structures used in linear algebra and data analysis, but they differ in their dimensions and representations.

## Vector: (It has only row or column)
#### - A vector is a one-dimensional array of numbers.
#### - It represents a quantity that has magnitude and directions.
#### - In mathematics, vectors are often denoted as column vector but they can also be represented as row vectors.

In [ ]:
## reshape() fn:
## numpy.reshape() fn shapes an array without changing the data of the array.

In [28]:
a = np.arange(8)
print("Original array: \n",a)

Original array: 
 [0 1 2 3 4 5 6 7]


In [32]:
# Shape array with 2 rows and 4 columns

b = np.arange(8).reshape(2,4)
print("\n Array reshaped with 2 rows and 4 columns: \n",b)


 Array reshaped with 2 rows and 4 columns: 
 [[0 1 2 3]
 [4 5 6 7]]


In [33]:
b = np.arange(8).reshape(2,2) # (2,2)-it can't reshape the dimension because range is 8 it only divide 2,4 numbers only....
print("\n Array reshaped with 2 rows and 4 columns: \n",b)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [34]:
# Constructors 3D array

d = np.arange(8).reshape(2,2,2)
print(d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [35]:
d = np.arange(8).reshape(8,)
print(d)

[0 1 2 3 4 5 6 7]


In [36]:
d = np.arange(8).reshape(8,1)
print(d)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [37]:
d = np.arange(8).reshape(1,8)
print(d)

[[0 1 2 3 4 5 6 7]]


In [38]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [39]:
b.shape

(3, 2)

In [40]:
b.size

6

In [41]:
b_reshape = b.reshape(2,3)
print(b_reshape)

[[1 2 3]
 [4 5 6]]


In [43]:
b_reshape = b.reshape(3,2)
print(b_reshape)

[[1 2]
 [3 4]
 [5 6]]


## Indexing and Slicing in 2D numpy array

In [3]:
# Slicing 2D numpy array

import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a[1,1:4])  # [Row,Column]   # 1 - Row 1:4 - Column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [18]:
a = np.arange(48).reshape(8,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


In [9]:
# Indexing

a[3]

array([18, 19, 20, 21, 22, 23])

In [10]:
a[-1]

array([42, 43, 44, 45, 46, 47])

In [11]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [12]:
a[4:]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [13]:
a[:5]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
a[0:4]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# Returning column using indexing

# All rows of a single

In [24]:
a[3:5:,3:6]

array([[21, 22, 23],
       [27, 28, 29]])